name: DeployApp

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      pr_number:
        description: "PR number"
        required: true
        default: "0"
        type: string

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZ_CLIENT_ID }}","clientSecret":"${{ secrets.AZ_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZ_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZ_TENANT_ID }}"}'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      - name: Dotnet test
        run: |
          dotnet test --filter Category=Unit
      - name: Dotnet build and publish
        run: |
          dotnet restore
          dotnet build Jfi.DemoPrWeb --configuration Release
          dotnet publish Jfi.DemoPrWeb -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: "app-dev-jfi-pr-demo-${{ inputs.pr_number }}"
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      - name: logout
        run: |
          az logout
