name: ReviewApp

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  provision:
    uses: JoeIngledew/review-pr-demo/.github/workflows/terraform-apply.yml@main
    with:
      pr_number: ${{ github.event.number }}
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    secrets: inherit
  build_and_deploy:
    uses: JoeIngledew/review-pr-demo/.github/workflows/deploy-app.yml@main
    with:
      pr_number: ${{ github.event.number }}
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    needs: provision
    secrets: inherit
  cleardown:
    uses: JoeIngledew/review-pr-demo/.github/workflows/terraform-destroy.yml@main
    with:
      pr_number: ${{ github.event.number }}
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    secrets: inherit