name: Terraform

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  build_and_deploy:
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: JoeIngledew/review-pr-demo/.github/workflows/terraform-apply@main
        with:
          pr_number: ${{ github.event.number }}
      - uses: JoeIngledew/review-pr-demo/.github/workflows/deploy-app@main
        with:
          pr_number: ${{ github.event.number }}
  cleardown:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: JoeIngledew/review-pr-demo/.github/workflows/terraform-destroy@main
        with:
          pr_number: ${{ github.event.number }}