name: E2E

on:
  workflow_call:
    inputs:
      pr_number:
        description: "PR number"
        required: true
        default: "0"
        type: string

env:
  E2E__CI: 'true'
  E2E__BaseUrl: "https://app-dev-jfi-pr-demo-${{ inputs.pr_number }}.azurewebsites.net"

jobs: 
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      - name: Dotnet test
        run: |
          dotnet restore
          dotnet test --filter Category=e2e